name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04 # Jammy
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt -yq install python3-bashate
      - run: bashate *.sh
